### ISSUE TITLE
Error starting timer.

### ISSUE THREAD

**Issue by CajuCLC** [jcgoette/baby_buddy_homeassistant#101]
I have a button where I start the time and it's not working now.

Error:
```
This error originated from a custom integration.

Logger: custom_components.babybuddy.client
Source: custom_components/babybuddy/client.py:75
Integration: Baby Buddy (documentation, issues)
First occurred: 1:03:08 PM (1 occurrences)
Last logged: 1:03:08 PM

Could not create timers. error: {'start': ['Date/time can not be in the future.']}. Please upgrade to babybuddy v1.11.0. In the meantime, attempting to use 'now()'...
```
Button:
```
show_name: true
show_icon: true
type: button
tap_action:
  action: toggle
entity: switch.name_lastname_timer
icon: mdi:timer-outline
```

If I change to a date in the past it works. Strange that it was working 7 hours ago and now it won't work.

Edit: I am running Baby Buddy 1.14.0.

**Comment by jcgoette** [comment]
Pretty sure it isn't d/t the integration. 

https://github.com/jcgoette/baby_buddy_homeassistant/issues/82#issuecomment-1416531189

**Comment by CajuCLC** [comment]
Not sure what the issue was. I had to restart the k8s cluster I am running Baby Buddy and then everything worked fine again. Could be something with network, but I am using IP, not DNS. And the diaper buttons worked just fine.
oh well.
