### ISSUE TITLE
Sensors for total life time diapers and feeds logged

### ISSUE THREAD

**Issue by kmanan** [jcgoette/baby_buddy_homeassistant#104]
Is there a way to get 2 sensors:
1. Total count of diaper changes lifetime (all diaper changes in the db)
2. Total count of feeds logged 

i don’t know how to create sensors out of BB’s (or any app’s APIs)

**Comment by jcgoette** [comment]
Not currently. Closing this in favor of https://github.com/jcgoette/baby_buddy_homeassistant/issues/58.
