### ISSUE TITLE
's' got stripped from the last name. 

### ISSUE THREAD

**Issue by pataar** [jcgoette/baby_buddy_homeassistant#11]
https://github.com/jcgoette/baby_buddy_homeassistant/blob/080c37f5ed3ae5e9f6c628ce77e638eb037ee6ef/custom_components/babybuddy/sensor.py#L105

Hey @jcoette, I have a small problem.  The 's' is stripped from the last name in the interface of HA. I guess it's because of this line. Is this needed?

**Comment by jcgoette** [comment]
It's not _needed_, but I prefer the look of it.

Anywho, fixed in v1.2.1. Thanks for reporting this!

**Comment by pataar** [comment]
Thanks :)
