### ISSUE TITLE
Unknown Error on setup

### ISSUE THREAD

**Issue by smarinel** [jcgoette/baby_buddy_homeassistant#110]
I am trying to configure the integration and getting a report of Unknown Error when entering what I understand to be the correct information. This is using 2.6.7 on an up-to-date Home Assistant installation. I can connect just fine to the baby buddy install and haven't setup anything else other than the standard Home Assistant packages. Any tips on why this could be failing? I am pretty new to home assistant and haven't messed around with HACS before. 

These are the only errors in the log: 

2023-05-24 07:54:24.217 ERROR (MainThread) [aiohttp.server] Error handling request
2023-05-24 07:55:56.506 ERROR (MainThread) [frontend.js.latest.202305033] :0:0 ResizeObserver loop completed with undelivered notifications.

**Comment by jcgoette** [comment]
I don't see anything useful here. Can you set your log levels to DEBUG?

**Comment by smarinel** [comment]
I ended up pointing this at an installation outside of Home Assistant and it worked just fine. I will try and recreate the issue and report back for posterity.

**Comment by jcgoette** [comment]
Ah, you were trying to set up with the BB addon. 

Maybe read through [#89](https://github.com/jcgoette/baby_buddy_homeassistant/issues/89).
