### ISSUE TITLE
Cannot connect integration to HASS deployed baby buddy

### ISSUE THREAD

**Issue by gioele-antoci** [jcgoette/baby_buddy_homeassistant#111]
No matter what combo I try I get a failed connect event. I am doing something dumb I know, but can't figure this simple step out. I don't see any logs in the addons, even in debug mode.

![image](https://github.com/jcgoette/baby_buddy_homeassistant/assets/18650836/77bd6595-fdcc-4705-83f3-7fb4756cc996)

The host is the address my Hass is reachable at. What am I doing wrong?

**Comment by jcgoette** [comment]
Are you using the BB HA add-on? Or a locally hosted BB instance?

**Comment by gioele-antoci** [comment]
BB addon

**Comment by jcgoette** [comment]
Maybe read through [#89](https://github.com/jcgoette/baby_buddy_homeassistant/issues/89).
