### ISSUE TITLE
Change the host

### ISSUE THREAD

**Issue by JohnnyBigoud** [jcgoette/baby_buddy_homeassistant#112]
It is not possible to change the host for the integration without adding a whole new host which will break all dashboards / autmations since it creates new entities.

Where can the host be changed?

Example: I previously users http://babybuddy.domain and I want to switch to my local IP http://192.168.1.X 

(very cool integration nonetheless. This isn't really an issue)

**Comment by jcgoette** [comment]
https://github.com/jcgoette/baby_buddy_homeassistant/issues/98
