### ISSUE TITLE
Failed To Connect

### ISSUE THREAD

**Issue by gavinsauder** [jcgoette/baby_buddy_homeassistant#113]
Trying to add integration to home assistant causes this error.

Host: https://babybuddy.sub.domain.com
Port: 443
API: ********************

This causes a failed to connect error. I'm using all the correct info but does not work.

**Comment by jcgoette** [comment]
https://github.com/jcgoette/baby_buddy_homeassistant/issues/111#issuecomment-1590982185

**Comment by rwelsh09** [comment]
After reading through both threads you mention I haven't found a solution for connecting the integration to the add-on

**Comment by rwelsh09** [comment]
[Solution!](https://github.com/jcgoette/baby_buddy_homeassistant/issues/103#issuecomment-1474384825) 

The port has to be manually set. This isn't mentioned in the setup instructions.

**Comment by jcgoette** [comment]
Cool. Sounds like something you should bring up on the addon's repository.

**Comment by gavinsauder** [comment]
This solution may work for the addon on. But I'm not using the addon. That solution does not work for my use case.

**Comment by jcgoette** [comment]
Is your BB actually located at a sub-subdomain like your post suggests?

**Comment by gavinsauder** [comment]
@jcgoette yes, thats correct. Its hosted in a docker container. It can be accessed directly just fine. But unable to add to HA integration.

**Comment by jcgoette** [comment]
Set logs to DEBUG and post what you see. There should be at least a line showing `Client URL:`

**Comment by gavinsauder** [comment]
I think this is what your asking for. I confirmed these are the correct urls before redacting them.

`2023-08-07 19:32:42.861 DEBUG (MainThread) [custom_components.babybuddy.client] Initializing BabyBuddyClient
2023-08-07 19:32:42.861 DEBUG (MainThread) [custom_components.babybuddy.client] Client API Token, obfuscated: 1da7................................6328
2023-08-07 19:32:42.861 DEBUG (MainThread) [custom_components.babybuddy.client] Client URL: https://babybuddy.***.*********.com:443
2023-08-07 19:32:42.862 DEBUG (MainThread) [custom_components.babybuddy.client] GET URL: https://babybuddy.***.*********.com:443/api/`

**Comment by jcgoette** [comment]
Does the Failed to connect error happen right after that line? Or is there more?

Is your HA instance reaching external web services for anything else?

**Comment by gavinsauder** [comment]
Ah I got it. My bad. My HA Instance is on a different vlan than my docker server/babybuddy. I needed to allow it through my 
 firewall to enable access from HA to babybuddy. Your comment helped me realize my error. Thanks for your time.
