### ISSUE TITLE
$firstname_$lastname_last_timer no longer has 'Active' attribute when a timer is active

### ISSUE THREAD

**Issue by drpeppershaker** [jcgoette/baby_buddy_homeassistant#117]
I've been using [this popular blueprint](https://community.home-assistant.io/t/baby-buddy-log-tummy-time-sleep-feeding-diaper-change-pumping/488156) to interact with HA and this integration for some time now.

If you read through the template, it uses `value_template: "{{ state_attr(_bb_child_last_timer, 'active')` and as far as I can tell, the ***_last_timer sensor no longer has an active attribute?

I don't know if this is a mistake or if this is now intended. If it's intended, I can update my local version of the blueprint to use something like `value_template: "{{is_state('switch.$firstname_$lastname_timer', 'on')}}"`. And raise the issue with the author of the blueprint.

**Comment by jcgoette** [comment]
Are you on latest BB? There are [now _only_ active timers](https://github.com/babybuddy/babybuddy/issues/109) and the `Active` key [was removed from BB/API](https://github.com/babybuddy/babybuddy/commit/7b7f17fde6cc6c45a36752cbf1b2752fe396476d).

Needs to be handled by the blueprint author.

**Comment by drpeppershaker** [comment]
Okay, awesome. Thank you for the speedy response! I'll raise it with he blueprint author
