### ISSUE TITLE
Home Assistant 2023.8.0: Invalid Device Info

### ISSUE THREAD

**Issue by droans** [jcgoette/baby_buddy_homeassistant#119]
Log:

```
2023-08-02 17:13:13.904 ERROR (MainThread) [homeassistant.components.sensor] Ignoring invalid device info: Invalid device info {'configuration_url': 'http://XXX.XXX.XX.XX:XXXX/children/xxxxx/dashboard/', 'default_name': 'Baby XXXXX ', 'identifiers': {('babybuddy', 2)}} for 'babybuddy' config entry: device info needs to either describe a device, link to existing device or provide extra information.
```

It appears that all entities are separated from the device, causing the Add Feeding and Add Change services to break if you use the device as the target. I am unsure if it affects other services.

**Comment by jcgoette** [comment]
Looks like this became an error with [2023.8](https://github.com/home-assistant/core/blame/82f27115f5b53074fa385cd571c37115544efbe8/homeassistant/helpers/device_registry.py#L129). (I didn't see anything in the dev blog 🤔)

We already provide `identifiers`, so probably just need to add `connections` to meet `link` criteria ([per docs.](https://developers.home-assistant.io/docs/device_registry_index/#categorizing-to-device-info))

**Comment by Borlean** [comment]
Same issue for me. 

I'm downgrading HAOSS for now and will keep an eye on any updates.

**Comment by cwgannon** [comment]
Workaround for me was pointing scripts and automations at the timer entity instead of the baby "device."

**Comment by droans** [comment]
> Looks like this became an error with [2023.8](https://github.com/home-assistant/core/blame/82f27115f5b53074fa385cd571c37115544efbe8/homeassistant/helpers/device_registry.py#L129). (I didn't see anything in the dev blog 🤔)
> 
> We already provide `identifiers`, so probably just need to add `connections` to meet `link` criteria ([per docs.](https://developers.home-assistant.io/docs/device_registry_index/#categorizing-to-device-info))

Thanks for your work! Wonder if it would be easiest to use a semi-random MAC with the last hex pair for the Child ID? Or you could use `via_device` with the BB instance itself, but I'm not sure if that will work.

Not trying to put pressure on you - do you think you'll have this updated soon? I'll be updating soon and I just need to know if I should go ahead and point all my scripts to the timer or not :)

**Comment by gagebenne** [comment]
Removing `default_name` seems to get things working again. The identifier is unique enough, not sure if there is a need to replace it with something.

**Comment by droans** [comment]
> Removing `default_name` seems to get things working again. The identifier is unique enough, not sure if there is a need to replace `default_name` with something -- if so, child slug could be used (it is unique).

Tried it out and it works on my end. It also seems like changing `default_name` to just `name` also works.

**Comment by jcgoette** [comment]
Closing in favor of #127.
