### ISSUE TITLE
Every upgrade of Baby Buddy app causes duplicate entities in HomeAssistant

### ISSUE THREAD

**Issue by adampetrovic** [jcgoette/baby_buddy_homeassistant#123]
Hi. I am currently running the latest BabyBuddy version (2.0.4) and have noticed with every version bump that my entities in HomeAssistant get recreated with a `_2` suffix and I have to delete the original and rename everything, which is a little tedious.

Any ideas why this is happening?

![CleanShot 2023-08-05 at 08 48 41@2x](https://github.com/jcgoette/baby_buddy_homeassistant/assets/88030/a3a7c4aa-78b3-4c04-915f-d4d5e6a6c48a)

**Comment by jcgoette** [comment]
The only thing that springs to mind would be if you're API key is changing with each upgrade? I kind of doubt that though.

**Comment by adampetrovic** [comment]
The integration doesn't have any problem with authenticating after Baby Buddy upgrades, it seems that it tries to recreate the entities every time rather than re-using the existing entities.

**Comment by jcgoette** [comment]
Anything interesting in the logs?

**Comment by jcgoette** [comment]
>1 month old, no reply. Closing as stale for now.

**Comment by atjacobs** [comment]
This happened to me. My baby buddy server went down (shutdown server). When I brought it back up, HA complained that the API key was wrong. Copy-pasted from baby buddy, and now all the old sensors are defunct and new ones have no data.

<img width="290" height="449" alt="Image" src="https://github.com/user-attachments/assets/4cef2e0c-1a65-49a4-a9eb-c9ee8b4eeead" />
