### ISSUE TITLE
Feeding Starting Date <> End Date

### ISSUE THREAD

**Issue by Quotenjunkie** [jcgoette/baby_buddy_homeassistant#125]
Hi,

with "Sleep" it is possible to specify a starting date that does not equal the end date. If I try the same thing with the feeding service then no entry will be created unless the starting date equals the end date.

Am I doing something wrong or how would you enter a feeding that starts right before midnight and ends on the next day?

BR

**Comment by Quotenjunkie** [comment]
Hi,

```
Logger: custom_components.babybuddy.client
Source: custom_components/babybuddy/client.py:75
Integration: Baby Buddy ([documentation](https://github.com/jcgoette/baby_buddy_homeassistant), [issues](https://github.com/jcgoette/baby_buddy_homeassistant/issues))
First occurred: 23:02:53 (2 occurrences)
Last logged: 23:04:33

    Could not create feedings. error: {'non_field_errors': ['Duration too long.']}. Please upgrade to babybuddy v1.11.0. In the meantime, attempting to use 'now()'...
```

But the addon is listed as v2.0.4. If I use Baby Buddy directly then it works flawlessly.

BR

**Comment by jcgoette** [comment]
Hmm. The part after "error:" is coming directly from BB, so I'm thinking something isn't being done exactly the same when it works directly in BB.

**Comment by Quotenjunkie** [comment]
Hi,

sorry for not respoding so quickly but as you expect the "little man" needs a lot of attention.

I´ve tried to replicate and document the error. It seems that if I use a date/time helper then Home assistant deletes the first zero of the time (so instead of 00:05 to 0:05)

If I overwrite the time again then it works.

BR
