### ISSUE TITLE
Set up Integration in yaml rather than HACS

### ISSUE THREAD

**Issue by gth758y** [jcgoette/baby_buddy_homeassistant#126]
I'm wondering if it's still possible to set up this integration via yaml rather than HACS. I'm running and older, pre-HACS build of Home Assistant and am trying to avoid an upgrade because of the breaking changes that will need to be corrected when I do.

I took the files from here and placed them into my custom integrations folder, but wasn't sure what to put in the yaml files - I tried unsuccessfully with a few syntaxes in both my sensors file and the top level config.

Thanks!

**Comment by jcgoette** [comment]
There is no **need** for HACS for any integration AFAIK.

**Comment by gth758y** [comment]
Okay, perfect - that was also my understanding.

I've tried adding it as a sensor based on the old README.md file, but get an invalid configuration error. Is there some other way I should be configuring? Thanks!

```
- platform: babybuddy
   address: https://10.x.x.x
   port: 8000
   path: ""
   api_key: !secret babybuddy_api_key
```

> Configuration invalid: Platform error sensor.babybuddy - cannot import name 'SensorDeviceClass' from 'homeassistant.components.sensor' (/usr/src/homeassistant/homeassistant/components/sensor/__init__.py)

**Comment by jcgoette** [comment]
It seems like maybe you are on a version of HA that is old enough it doesn't have certain classes the integration uses?

**Comment by gth758y** [comment]
Could be.. I'm on 2021.8.6 -- I'll keep playing with it and maybe I'll just have to suck it up and upgrade. Appreciate it!
