### ISSUE TITLE
Can't seem to connect Baby Buddy to Home Assistant

### ISSUE THREAD

**Issue by milkplus27** [jcgoette/baby_buddy_homeassistant#13]
Hi there. Firstly, thank you for creating this integration. I'm about 3 weeks away from my first child being born and would like to be able to incorporate some kind of logging system into HA so that my partner and I can keep track of what has/hasn't happened with the baby,

I am totally green when it comes to a lot of this stuff so have been fumbling my way through setting up a working Home Assistant setup that i'm currently happy with but have been really struggling to get Baby Buddy up and running. I first tried installing it using Docker Compose on a Raspberry Pi 3B, which I have some other containers running on without issue. But I couldn't for the life of me figure out Baby Buddy. The database seem to generate well enough but i can't connect to the app via the local IP address.

After several hours reading over the various threads on the repo, and feeling very in over my head, i thought i'd give it a shot setting it up via the Heroku method. why not? I wasn't holding out much hope but i registered an account and hit the "Deploy to Heroku" button on the Baby Buddy repo and lo and behold, it installed and worked without a hitch. I now have an external URL hosted on Heroku that I can access a Baby Buddy instance. hooray!

However, this victory was quickly quashed as I now can't seem to connect it to HA via that URL. Seemed like it should be easy, no? I installed your component and setup my config like so:

```
sensor:
 - platform: babybuddy
     address: http://*****.herokuapp.com/
     api_key: **************
     ssl: false
```

Rebooted HA and crossed my fingers - but no cigar. No senors populated into HA after a reboot. I even tried creating a few sleep and tummy time events in Baby Buddy as I thought that perhaps it wouldn't create sensors if the logs were empty, but still nada.

I'm really not sure what I'm doing wrong. Any advice or troubleshooting tips you might have would be super appreciated.

**Comment by jcgoette** [comment]
I can try and help. Please post your Home Assistant error log.

**Comment by milkplus27** [comment]
thank you let me track it down

**Comment by milkplus27** [comment]
ahh actually! i managed to sort it. turns out i needed to remove the "http://" from the URL as it was posting it like this when trying to connect: "http://http://*****.herokuapp.com/"

Now i can see 3 sensors created. one for the baby, and for last_sleep and last_tummy_time. Should have checked the logs from the start! rookie mistake. Thanks for pointing me in the right direction :)

Are you familiar with Heroku at all? i'd much rather have Baby Buddy running locally on a raspberry Pi, but it was such a struggle getting this far that i'm nervous to futz around with anything further now that I have it running.

Also, now that the sensors are populated are they treated just like other entities in HA - meaning i can just place them in a card to view on my dashboard? I noticed that it's not possible to send info to Baby Buddy yet via this integration... in my reading earlier i saw someone had setup a button system to update Baby Buddy via Node Red/MQTT, may have to look into that next.

**Comment by jcgoette** [comment]
> Are you familiar with Heroku at all? i'd much rather have Baby Buddy running locally on a raspberry Pi

Not really. I run Baby Buddy via Docker and recommend that.

> Also, now that the sensors are populated are they treated just like other entities in HA - meaning i can just place them in a card to view on my dashboard?

Yes.

> I noticed that it's not possible to send info to Baby Buddy yet via this integration...

Not yet. See issue #6.
