### ISSUE TITLE
Integration setup keeps failing to connect, using Nabu Casa

### ISSUE THREAD

**Issue by RyChOr** [jcgoette/baby_buddy_homeassistant#130]
No matter what I try I seem to be getting the 'Failed to connect' error

Host: https://**********************.ui.nabu.casa
Port: 8889 (Which is also added in the Baby Buddy Add-On -> Configuration -> Network section)
Path: (blank)
API Key: ************************* (Taken from the Baby Buddy instance -> User Settings)

Not sure if this is a port forwarding issue or not.  Unfortunately, networking is not my strong suit, but any help is appreciated here.  Thank you

**Comment by gagebenne** [comment]
Host should likely be a local host rather than `ui.nabu.casa`. For example, my Home Assistant is locally a `192.168.1.X` address and add-ons would be there. Add-ons, by design, likely aren't forwarded like Nabu Casa forwards your Home Assistant local instance.

**Comment by RyChOr** [comment]
Thank you so much. This did the trick.  One thing to note if anyone else is having this problem is that after entering the host address, do not include the forward slash or it will fail to connect.
