### ISSUE TITLE
Missing entities in 2023.9

### ISSUE THREAD

**Issue by socbrian** [jcgoette/baby_buddy_homeassistant#133]
I only have 4 entities showing up with the baby buddy integration. Re-setup the API and issue still persist. Getting error in logs: 

`
babybuddy: Not adding entity with invalid device info: Invalid device info {'default_name': 'baby', 'identifiers': {('babybuddy', 2)}} for 'babybuddy' config entry: device info needs to either describe a device, link to existing device or provide extra information. `

**Comment by jcgoette** [comment]
See #127.
