### ISSUE TITLE
Green Notification lines persist after dismissing them.

### ISSUE THREAD

**Issue by krasatos** [jcgoette/baby_buddy_homeassistant#137]
While setting up, I have created and deleted several feeding entries.
While deleting them I get the following notification pop ups that I cannot dismiss:
![image](https://github.com/jcgoette/baby_buddy_homeassistant/assets/1773624/7eaad93a-497f-4ef0-b22d-56174a1c3371)
I hit the X and they disappear but then in the next screen i visit they show up again.
Any idea how i can get rid of them?

**Comment by jcgoette** [comment]
This would be a question for the BB app, not the HA integration.

**Comment by krasatos** [comment]
Thank you & sorry, i will reach out to them.
