### ISSUE TITLE
missing users settings tab 

### ISSUE THREAD

**Issue by bembembene** [jcgoette/baby_buddy_homeassistant#138]
Hey all,

i didn't get it. i installed baby buddy over hacs and i have no clue where i get the api key and the rest of the parameters. I cannot find the users tab. Someone an idea?
greetings

**Comment by jcgoette** [comment]
You get it from within the BB app itself. Which requires you to be hosting BB somewhere externally or using the BB add-on.

**Comment by bembembene** [comment]
my bb addon isn't working. i installed it over hacs and cannot start the integration without the api.
<img width="1002" alt="grafik" src="https://github.com/jcgoette/baby_buddy_homeassistant/assets/54186348/895cc944-1c8c-4c21-85f7-feb3235bb7d4">
<img width="572" alt="grafik" src="https://github.com/jcgoette/baby_buddy_homeassistant/assets/54186348/c2a3b0d4-be09-4888-8d1c-77cfbe4386b1">
