### ISSUE TITLE
Baby buddy Integration only displays 11 entities , missing sensors

### ISSUE THREAD

**Issue by Wagner545** [jcgoette/baby_buddy_homeassistant#141]
The baby buddy integration is only displaying the following entities:

- select.baby_buddy_diaper_color
- select.baby_buddy_diaper_type
- select.baby_buddy_feeding_method
- select.baby_buddy_feeding_type
- sensor.baby_
- sensor._last_change
- sensor._last_feeding
- sensor._last_height
- sensor._last_timer
- sensor._last_weight
- switch._timer

According to the [documentation](https://github.com/jcgoette/baby_buddy_homeassistant#sensors) I should have the following: 

- last data entry, 
- including diaper_change
- feeding, notes
- sleep, 
- temperature
- tummy_time
- temperature
- weight.

**I'm currently missing**

- feeding, notes
- sleep, 
- temperature
- tummy_time
- temperature

I'm running baby_buddy_homeassistant integration 2.7.1. 
Add-on 68152197_baby_buddy! version 2.1.1.

Please let me know if you need any further details. Thank you for looking into this. I really appricate all the hard work that has been put into this amazing job.

**Comment by jcgoette** [comment]
Silly question, do you actually have that data in BB?

**Comment by xktder** [comment]
hahaha.

**Comment by McDAlexander** [comment]
For any sleep deprived users out there, if you are seeking specific sensors, but they appear to be missing, check the entities for attributes. I was able to find last feeding times, durations, methods, as attributes under the "last feeding" entity. This was not super apparent to me, so hopefully some sleep deprived parent finds this helpful in the future.
