### ISSUE TITLE
Adding weight unit of grams

### ISSUE THREAD

**Issue by fodi666** [jcgoette/baby_buddy_homeassistant#144]
Hi,
could you also add grams as the supported measurement units for the integration? Since our scale displays the number in grams it is much easier to enter them as such in the database, however now it shows as kilograms, pounds or ounces in Home Assistant.
Thanks

**Comment by jcgoette** [comment]
Fixed in https://github.com/jcgoette/baby_buddy_homeassistant/commit/10b9e7555910d3c54bee00d3702551b59147c741.
