### ISSUE TITLE
Pumping amount is always saved as integer, not float

### ISSUE THREAD

**Issue by 20BBrown14** [jcgoette/baby_buddy_homeassistant#147]
When using the `add_pumping` service, specifying a float for the amount is always saved as an integer (2.73 -> 2.0, 3.5 -> 3.0, etc) in baby buddy.
I have confirmed that the baby buddy API itself handles floats just fine and saved them as expected. For some reason, the add_pumping service doesn't honor the float and converts it to an integer.

**Comment by jcgoette** [comment]
Fixed by https://github.com/jcgoette/baby_buddy_homeassistant/commit/75c263a92682c5399ff919f212037a6ce6c6238d.
