### ISSUE TITLE
Deprecation warning log hass.helpers.aiohttp_client in 2024.11

### ISSUE THREAD

**Issue by jdahlgren** [jcgoette/baby_buddy_homeassistant#150]
Got a warning log in my HA stating the following three

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:190
First occurred: 11:46:47 (3 occurrences)
Last logged: 11:47:05

Detected that custom integration 'babybuddy' accesses hass.helpers.aiohttp_client. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from aiohttp_client directly at custom_components/babybuddy/__init__.py, line 131: hass.helpers.aiohttp_client.async_get_clientsession(),, please create a bug report at https://github.com/jcgoette/baby_buddy_homeassistant/issues

**Comment by jcgoette** [comment]
Thanks! Leaving this here for future reference:

https://developers.home-assistant.io/blog/2024/03/30/deprecate-hass-helpers/

**Comment by ProConvenience** [comment]
Small reminder that there's about a month left until 2024.11 is released, in which this integration will stop working.

I searched for where "hass.helpers" is used and found two files, but I'm not advanced enough to know what to do with them or if there are additional changes needed:
- [config_flow.py](https://github.com/jcgoette/baby_buddy_homeassistant/blob/75c263a92682c5399ff919f212037a6ce6c6238d/custom_components/babybuddy/config_flow.py#L81)
- [_\_init__.py](https://github.com/jcgoette/baby_buddy_homeassistant/blob/75c263a92682c5399ff919f212037a6ce6c6238d/custom_components/babybuddy/__init__.py#L131)

**Comment by jcgoette** [comment]
Closed by 6e621f0146cea969dc4f38441ef8efd1a2482f6f.
