### ISSUE TITLE
Authentication issue after last release

### ISSUE THREAD

**Issue by Aohzan** [jcgoette/baby_buddy_homeassistant#35]
Hello,

Since the last (big) update, I added the integration from UI successfully, but I only have 4 select entities and this error:
```
2021-09-05 12:47:51 ERROR (MainThread) [custom_components.babybuddy] Authentication failed while fetching babybuddy data: 403, message='Forbidden', url=URL('https://mybabybuddy/api/children/')
```
On babybuddy :
```Forbidden: /api/children/```

I tried to reset my api key multiple times but same issue :(

**Comment by jcgoette** [comment]
Check this:

https://gitter.im/babybuddy/Lobby?at=612f62e87cd57813a89fadee

**Comment by Aohzan** [comment]
Great thank you,
Is it normal that last_feeding entity state stay at unknown but attributes are all ok :
![image](https://user-images.githubusercontent.com/2736322/132125425-15d3bac1-cd08-4f69-982f-8e27dfbeda54.png)

**Comment by jcgoette** [comment]
See https://github.com/jcgoette/baby_buddy_homeassistant/pull/33#discussion_r698911200.
