### ISSUE TITLE
Example script needed

### ISSUE THREAD

**Issue by sfgrabowski** [jcgoette/baby_buddy_homeassistant#41]
My son has now been born and we've started using the integration. I had previously set up a series of buttons in HA that logged feeds and changes to BB without any issue. This is an example of the script called by a button press:

`service: babybuddy.services_feedings_add
data:
  child: sensor.baby_grabowski
  type: Breast milk
  method: Left breast
  amount: '1'
  start: '{{ now() }}'
  end: '{{ now() }}'`

For changes I used:

`service: babybuddy.services_changes_add
data:
  child: sensor.baby_grabowski
  time: '{{ now() }}'
  wet: false
  solid: true
  color: Black`

With the recent updates to the integration, this no longer works as I believe it is looking for a timer. I can't figure out what to do (especially with the sleep deprivation!). Can someone suggest how to edit the above script to be able to quickly log a feed with the required attributes. I'm not bothered about how much or how long (for now) as I simply wanted the feed to be logged. As I said, this worked fine before the recent updates, but the readme isn't detailed enough for me to figure out integrating timers etc.

Any help is MUCH appreciated (especially for the very tired WAP factor!!)

**Comment by jcgoette** [comment]
Something like this should work:

```
service: babybuddy.add_feeding

target:

  entity_id: switch.baby_grabowski_last_timer

data:

  type: Breast milk

  method: Both breasts
```

**Comment by sfgrabowski** [comment]
Thanks for this but it doesn’t seem to update BB when I run the script. I tried playing around with some of the different variables, but nothing updates on the BB dashboard.

**Comment by jcgoette** [comment]
The entity matches yours? Any log messages?

**Comment by sfgrabowski** [comment]
Ah ha! This was odd unexpected behaviour. The “switch” entity only appeared in the configuration section in HA after it had been used once. And for some reason it’s entity I’d was just switch.baby_last_timer rather than switch.baby_grabowski_last_timer as we both expected (to clarify I didn’t know the sex of our baby when I set everything up in August so just called it baby grabowski as a placeholder, but it works, so cba to change it now).

This is now working. Thank you!

One extra question (rather than creating a new ticket)… how do you get the last feed entity to show time since (like last change) rather than the amount (as amount isn’t any use for breast feeds). 

Thanks again
