### ISSUE TITLE
Prepare for Napping

### ISSUE THREAD

**Issue by jcgoette** [jcgoette/baby_buddy_homeassistant#49]
Per https://github.com/babybuddy/babybuddy/pull/325.

**Comment by jcgoette** [comment]
Closing until any design changes are implemented in BB.

**Comment by Dinth** [comment]
> Closing until any design changes are implemented in BB.

I think it has already been implemented, it would be awesome to have this in the integration though (ive got several zigbee buttons to switch on timer and stop the timer as sleep, but currently it only leaves a note if it was nap or night sleep and later on i need to go through all the entries and change them).

**Comment by jcgoette** [comment]
Closed by https://github.com/jcgoette/baby_buddy_homeassistant/commit/5a866bf65721998d6e35b880c6693110f1b07387.
