### ISSUE TITLE
Connecting issue

### ISSUE THREAD

**Issue by MaikelvdB07** [jcgoette/baby_buddy_homeassistant#50]
Please help me out.

I've deployed the Baby Buddy on Heroku, but when I try to integrate it in Home Assistant it asks for a host and API.

What do I enter as the host?

It keeps saying that it can't connect when I enter the URL.

Thanks in advance!

**Comment by jcgoette** [comment]
Go to your user settings within BB. Copy and paste the entire URL here.

Also, the API key will be at the bottom of this same screen.

**Comment by MaikelvdB07** [comment]
Thanks, but still get invalid autentication.

So the URL is ..../users/settings?

**Comment by MaikelvdB07** [comment]
https://babybuddy-hms.herokuapp.com/user/settings/

This should be the URL?

**Comment by jcgoette** [comment]
No, try `babybuddy-hms.herokuapp.com` as host and 443 as port.

**Comment by MaikelvdB07** [comment]
Thank you so much!!

**Comment by nckslater** [comment]
I've tried babybuddy-hms.herokuapp.com and https://babybuddy-hms.herokuapp.com with port 443 and my API key.
Now I get error 'failed to connect'

**Comment by artiscursive** [comment]
> 

Did you ever get it to work? Im currently running into the same issues. Ive tried every possible combination of the host / port / api key
