### ISSUE TITLE
I cant get the integration to showup on lates home assistant build

### ISSUE THREAD

**Issue by ecto1a2003** [jcgoette/baby_buddy_homeassistant#66]
I installed via hacs but nothing shows up anywhere

**Comment by jcgoette** [comment]
HACS

1. Navigate to integrations section.
2. Click "Explore & Add Repositories" in the bottom right corner.
3. Search for "Baby Buddy".
4. Click "INSTALL THIS REPOSITORY IN HACS".
5. Click "Install".

**Comment by ecto1a2003** [comment]
did that, forgot to hard refresh my browser. all good
