### ISSUE TITLE
Default Last Feeding Entity Shows as Unknown

### ISSUE THREAD

**Issue by ahgray** [jcgoette/baby_buddy_homeassistant#68]
Last feeding entity shows as unknown by default. The attribbutes seem to populate and work. I could create an attribute item as a work around but this seems like it should be a simple fix to have it work like the other entities, which do work by default.

![2022-06-15_12-35](https://user-images.githubusercontent.com/5378643/173900599-cd9e1d6e-3289-40ff-9ea0-f5c9cfe7bd32.png)

**Comment by jcgoette** [comment]
That's because it would show "Amount", but your amount value is null.

Potentially related to #45.
