### ISSUE TITLE
version number

### ISSUE THREAD

**Issue by chpego** [jcgoette/baby_buddy_homeassistant#71]
https://github.com/jcgoette/baby_buddy_homeassistant/blob/977bf941b5729a5115a67f79cc22c483c84335df/custom_components/babybuddy/manifest.json#L10

I think the version number has not been incremented for several versions

**Comment by jcgoette** [comment]
Closed by https://github.com/jcgoette/baby_buddy_homeassistant/commit/5ada3e6b52bbe47e0fd5533d676c7cb395da3660.
