### ISSUE TITLE
Add support for setting a note tag with add_note service

### ISSUE THREAD

**Issue by Cadair** [jcgoette/baby_buddy_homeassistant#77]
Unless I am missing something it seems that adding tags to notes isn't currently supported? This would be a nice addition. Thanks!

**Comment by Cadair** [comment]
Something else that I just thought of related to this is that it would be really nice to be able to get the time of the last note with a given tag, i.e. "last note with tag medicine"

**Comment by jcgoette** [comment]
That would be cool and seems doable based on existing API documentation.

**Comment by Cadair** [comment]
I found the [Octopus Energy](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy) custom component used [config flow's](https://developers.home-assistant.io/docs/config_entries_config_flow_handler/#defining-your-config-flow) to have an optional extra setup step to run which adds a new sensor for your energy rates.

We could do something similar to add sensors for notes (or other things) with specific tags?

**Comment by jcgoette** [comment]
Yea, that is one option.

Another option is to just automatically create sensors for the last x for each tag. Could create them as automatically disabled or otherwise.

**Comment by Marquo1** [comment]
Really wish this was in. Would be handy for recording solid foods

**Comment by ViPeR5000** [comment]
+1

**Comment by TygerrZA** [comment]
Is it possible to add tags with the other services (diaper changes, feedings, sleep, etc)? Or is this not possible via the API?

**Comment by jcgoette** [comment]
Looks possible to me.

**Comment by TygerrZA** [comment]
> Looks possible to me.

Sorry - just to clarify: do you mean it is currently possible to do this (if so, what is the JSON key to use?).
Or do you mean it can be added in as a later enhancement?

**Comment by jcgoette** [comment]
Could be added. https://github.com/jcgoette/baby_buddy_homeassistant/issues/77#issuecomment-1321137742

**Comment by acmill14** [comment]
Hi, was there ever support added to add tags in service calls? Specifically the "add diaper change" one. Or if there's an example of how to do this in YAML I'd appreciate it!

**Comment by jcgoette** [comment]
Closed by https://github.com/jcgoette/baby_buddy_homeassistant/commit/a84d10fb8f138919fdf3fce028c03bf503dd54d3.
