### ISSUE TITLE
Options is available as a standard property of SelectEntityDescription

### ISSUE THREAD

**Issue by epenet** [jcgoette/baby_buddy_homeassistant#80]
As of Home Assistant Core 2022.11, options is available as a standard property of SelectEntityDescription.
This may cause issues in custom components if a custom options property was previously implemented.

Please adjust the custom component by either dropping or renaming the custom options property.

See https://github.com/home-assistant/core/pull/78882

**Comment by jcgoette** [comment]
Nice. If I'm reading this correctly, just delete https://github.com/jcgoette/baby_buddy_homeassistant/blob/1e570f84d17297a719aa433373331ba4141b6663/custom_components/babybuddy/const.py#L183, right?

Did you want to PR? Or fine with me handling?

**Comment by jcgoette** [comment]
Closed by cddb62c050b65dab3e0812472947c13edd231048. Thanks @epenet!
