### ISSUE TITLE
Use Google Assistant to start and stop timers?

### ISSUE THREAD

**Issue by poldim** [jcgoette/baby_buddy_homeassistant#81]
I'd like to setup GA to start a feeding timer and a sleep timer from a voice command. Since I'm using this with HA, I can use the `start_timer` service on entity `switch.kai_timer`.  Before I try to have these actions work with voice, I need them to work with HA on its own. I can't seem to figure out how to stop and tag the timer correctly. 

- The `switch.kai_timer` entity appears to turn on if a timer is running. But if I simply turn off this switch, it appears to **delete** the timer which is not desired. Can I stop the timer without deleting it?
- Is there a way to tag the timer to a given activity like feeding or sleep?

**Comment by jcgoette** [comment]
https://github.com/jcgoette/baby_buddy_homeassistant#switches

**Comment by poldim** [comment]
> https://github.com/jcgoette/baby_buddy_homeassistant#switches

That wasn't helpful as I had already seen it but this time I searched for timer and found it later on in the feeding and sleep sections which I didn't see before.  Thanks!

![image](https://user-images.githubusercontent.com/16869713/195913274-39dc83ff-22cc-4c1c-9c12-c6706e450040.png)

![image](https://user-images.githubusercontent.com/16869713/195913335-9432a549-3f30-45f6-8bbf-9a832964b9ce.png)
