### ISSUE TITLE
I don't understand the timer workflow

### ISSUE THREAD

**Issue by AndreKR** [jcgoette/baby_buddy_homeassistant#85]
So how am I supposed to add a feeding using the timer?

I start the timer, then I call the "Add feeding" service with `entity_id` of the timer and _also_ `timer` = True and then when the feeding ends I turn off the timer? That doesn't work for me, the feeding is created with identical start and end time and is never updated.

**Comment by jcgoette** [comment]
Calling a service with an active timer passed in should consume the timer and use the timer's start instant.

**Comment by AndreKR** [comment]
Ah yes, it does now. Turns out I didn't actually set `timer` to True.
