### ISSUE TITLE
Only shows 4 entities

### ISSUE THREAD

**Issue by TaddyJ** [jcgoette/baby_buddy_homeassistant#86]
Hi,
I had Baby Buddy working fine for ages on Hass. Then it broke for a while and I was too lazy to fix it. recently I did tho and I've lost access to all the different sensors etc.
The only things I have access to now are Diaper color/type, Feeding method/type.. I try searching for other sensors and I get nothing unfortunately. Even when I do a search through everything and I type in "sleep" I get everything else but a baby buddy sensor.. 

Not sure if I'm doing something wrong or its currently broken.
I would like to set up notifications based on last sleep etc.
attached is a picture of all it shows in the settings.

![image](https://user-images.githubusercontent.com/60259158/209952729-e5ff383f-3cd5-43dd-9584-b32fcfd608f6.png)

**Comment by jcgoette** [comment]
Not much to go on here... 

- What does BabyBuddy look like in Devices & Services? 

- Anything in the logs? 

- Have you tried resetting the integration from scratch?

**Comment by TaddyJ** [comment]
In devices & Services;
![image](https://user-images.githubusercontent.com/60259158/210060521-ca3160f0-18ef-4ac6-a9fe-d0f448193f2d.png)

Logs;

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/babybuddy/__init__.py", line 198, in async_update
    if children_list[ATTR_COUNT] < len(self.child_ids):
KeyError: 'count'

Resetting;
Yeah I have. it says I need a path. but default I leave blank or put " " as stated but nothing

**Comment by jcgoette** [comment]
Did you use `" "` or `""` as path?

**Comment by TaddyJ** [comment]
I did " " 
Should I leave it without a space?

**Comment by TaddyJ** [comment]
I just tried re adding it again with both combinations of "" and " ". each time it says "Failed to connect.
I leave it out completely and it connects but with no sensors. just the 4 as stated in the previous post.

Is it maybe because I played around with a second child before (Now deleted). It may not have a default path?

**Comment by jcgoette** [comment]
I don't think that should matter if you removed the integration and added from scratch. Any additional logs? Do you have `DEBUG` log levels on?

**Comment by TaddyJ** [comment]
Yeah re added from scratch. Unfortunately I cannot put either "" or " " into the Path section. It will only add if I leave it blank completely.

I'll turn on debugging but if it cant pull it because its not properly integrated. not sure debugging will help.

**Comment by TaddyJ** [comment]
With Debugging enabled.
![image](https://user-images.githubusercontent.com/60259158/210124505-5aef57e4-b225-48dd-a3af-45770c9f37c9.png)

Logger: custom_components.babybuddy
Source: custom_components/babybuddy/__init__.py:198
Integration: Baby Buddy ([documentation](https://github.com/jcgoette/baby_buddy_homeassistant), [issues](https://github.com/jcgoette/baby_buddy_homeassistant/issues))
First occurred: December 30, 2022 at 6:28:48 PM (1060 occurrences)
Last logged: 12:12:16 PM

Unexpected error fetching babybuddy data: 'count'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/babybuddy/__init__.py", line 198, in async_update
    if children_list[ATTR_COUNT] < len(self.child_ids):
KeyError: 'count'

**Comment by jcgoette** [comment]
Hmm. Based on error and the code in that section, it looks like you don't have any children in your BB instance?

**Comment by foxalerts23** [comment]
I have a similar problem, but logs show a different error.

`Unexpected error fetching babybuddy data: 'count'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/babybuddy/__init__.py", line 198, in async_update
    if children_list[ATTR_COUNT] < len(self.child_ids):
KeyError: 'count'`

**Comment by TaddyJ** [comment]
> Hmm. Based on error and the code in that section, it looks like you don't have any children in your BB instance?

I do... haha. I've been tracking him for over a year! 

That being said and similar to Foxalerts, 
Even tho they have since been deleted. I have experimented with multiple "Children" for tracking my wifes expressing etc.

Maybe when there is multiple children the "Path" is coded different... and if it is maybe, or even if its not... the doccumentation is pretty scarce for my smooth brain to figure out where to even find the "Path" to try to fix it myself??

**Comment by jcgoette** [comment]
Path is just related to [this.](https://github.com/jcgoette/baby_buddy_homeassistant/pull/67)

@foxalerts23, have you also added and deleted children?

**Comment by TaddyJ** [comment]
> Path is just related to [this.](https://github.com/jcgoette/baby_buddy_homeassistant/pull/67)

Possibly... To be honest I'm not really able to understand the commit/contribution side of things. 

Is there a way for you to tell me where to find the "Path" for where my "Child" would be located so I can add it manually?

Another option would be that instead of trying to look for a child in the default path.. Maybe with its ability to pull data based on the api, Could it ask you what child based on the information returned. That way for people like Fox he can have multiple instances for each children if he wants?

**Comment by jcgoette** [comment]
It does pull from BB API. 

The path option probably doesn't apply to you (unless you host your BB instance in a path, e.g., `https://www.TaddyJ.com/BabyBuddy/`)

**Comment by jcgoette** [comment]
Also, with log levels set to DEBUG, I would expect to see something with `GET URL` and `GET response`.

**Comment by TaddyJ** [comment]
There ya go.... 
Pulling https://myurl/ port 443 (Path left blank) and the API its pulled 16 different entities.

Not sure why I cant do that across my local network tho...

**Comment by jcgoette** [comment]
Not sure what you mean, but it sounds like this is resolved. 🙂

**Comment by foxalerts23** [comment]
> Path is just related to [this.](https://github.com/jcgoette/baby_buddy_homeassistant/pull/67)
> 
> @foxalerts23, have you also added and deleted children?

I did add a child.
I deleted the integration (which worked previously) and attempted to re-install.
Let me know if I should start a new issue/question.

**Comment by TaddyJ** [comment]
> Not sure what you mean, but it sounds like this is resolved. 🙂

It appears to be... But I'm not sure why its able to work with an external url rather than an internal IP address as a host.

**Comment by TaddyJ** [comment]
Not sure if this should be closed out if Foxalerts is still having a similar issue.
And because I found a work around doesnt really mean there still isnt the underlying issue of why I have to use an external facing address rather than a local IP/Port..

**Comment by jcgoette** [comment]
Did you update BB and it stopped working? If so, read through https://github.com/jcgoette/baby_buddy_homeassistant/issues/60.
