### ISSUE TITLE
STOP_TIMMER

### ISSUE THREAD

**Issue by randyesperben** [jcgoette/baby_buddy_homeassistant#87]
Hi all!

I'm using the START_TIMER service to start a timmer, but I need a service to stop it as well. It's possible?

Thanks in advance!

**Comment by jcgoette** [comment]
https://github.com/jcgoette/baby_buddy_homeassistant/issues/85#issuecomment-1365623447

**Comment by randyesperben** [comment]
Hi @jcgoette 
Thanks for your reply, but I don't understand how to do it.
START_TIMER service doesn't allow an identifier. just "start_time" and "name".
Every time I call the service, it creates a new timmer.

Many thanks in advance!
