### ISSUE TITLE
Diaper type went from `type` to `diaper_type`

### ISSUE THREAD

**Issue by poldim** [jcgoette/baby_buddy_homeassistant#91]
Yesterday I did some updates and when I got up this morning the WAF was low as "baby buddy wasn't working".  Doing some digging, I found this change that was breaking my automations.  I searched for any breaking changes notes and didn't see anything.  Did I just miss these?  If not, it'd be helpful if those were documented somewhere prior to pushing the update.

**Comment by jcgoette** [comment]
Thanks for posting. This was unintended and fixed in 1169809b06af8352bc2a62749ad133d5f4ea54d3.
