### ISSUE TITLE
add support: get old data (weight etc)

### ISSUE THREAD

**Issue by jetijeti** [jcgoette/baby_buddy_homeassistant#92]
would it be possible to grab the old weight/size/temperature data from the baby buddy instance.
right now only the data trasmitted by homeassistant is shown.

**Comment by jcgoette** [comment]
It would be possible. Related to [this update to BB API.](https://github.com/babybuddy/babybuddy/pull/442)

What would the use-case in HA be? I'm wondering if this might be related to https://github.com/jcgoette/baby_buddy_homeassistant/issues/57 also. 

I'm open to PRs.

**Comment by jetijeti** [comment]
The Usecase would be to integrate data of measurements of an already existing BB instance into HA (as I had). I exportet and imported everything into the new BB provided by your integration, so the data is available in the new BB but not HA. 
My suggestion sounds very similar to #57. After reading #57 i guess the biggest challenge is getting the data into HA as the sensor: "sensor.baby_last_xxx (weight, feeding, etc)" only has the Information of the last weight, feeding etc. :-(
I already tried to modify my sqlite database but bricked my db several times doing so.

**Comment by jcgoette** [comment]
It sounds like you might be confusing this integration with the [addon](https://github.com/OttPeterR/addon-babybuddy).

Either way, a sensor could be created to  return data other than the latest, but that doesn't seem to be the end result you want.

**Comment by jetijeti** [comment]
I guess you are somewhat right with me confusing the addon and integration.
I will link this issue there and start a new "feature request "
Thanks

**Comment by jcgoette** [comment]
I don't think that's the answer. The addon shouldn't be much different from BB itself.

**Comment by jetijeti** [comment]
So Integration and addon would need to be adapted to make this possible?
