### ISSUE TITLE
Sensors Not Polling Without Service Call

### ISSUE THREAD

**Issue by tango2590** [jcgoette/baby_buddy_homeassistant#93]
I've noticed that sensors won't poll data unless that respective service is called. When data is added via the HA frontend by calling a specific service (such as add_feeding), the sensor is polled and data is updated. However, data added directly into BabyBuddy via the add-on is not reflected in the sensor until that respective service is called to POST the data. Is it possible to add a poll service to just GET all data from the BabyBuddy add-on as needed?

**Comment by jcgoette** [comment]
That should not be true. You may need to configure the integration differently:

![image](https://user-images.githubusercontent.com/53531335/213033810-0b08fc5a-6daa-4149-8f2a-8fbe30d45a1e.png)
