### ISSUE TITLE
Is there a way to edit the host IP that was entered during setup?

### ISSUE THREAD

**Issue by kmanan** [jcgoette/baby_buddy_homeassistant#98]
Hi, I'm back with a new issue. I changed my network and the RPi that hosts BB has a new IP. The integration has stopped working because the host IP is different. Is there a way to change the host IP? I have Studio Code Server and can access the config section. I tried searching through there and didn't find anything.

**Comment by jcgoette** [comment]
Simplest answer is to just re-setup the integration.

**Comment by ICULikeMac** [comment]
This will reset all the entities in HomeAssistant so all scripts/automation will need to be updated at the same time? Is there any other way? Thanks!

**Comment by jcgoette** [comment]
>reset all the entities in HomeAssistant so all scripts/automation will need to be updated

Not sure what you mean by this... 

>Is there any other way?

I'm sure there is, but I don't know how off the top of my head.

**Comment by zakhenry** [comment]
from what I can find the thing to edit is the `DOMAIN` const in `config/custom_components/babybuddy/const.py`
